#!/usr/bin/python

from pybrate import Dryer
from pyfttt import sending
from time import sleep

import argparse

parser = argparse.ArgumentParser(description='Send dryer notifications')
parser.add_argument('--key', '-k', default=False, required=True,
        help="IFTTT API key")
args = parser.parse_args()
apikey = args.key

myDryer = Dryer()

while True:
    if myDryer.update():
        if myDryer.running:
            sending.send_event(apikey, "dryer_started")
        else:
            sending.send_event(apikey, "dryer_finished")
    sleep(5)

